### ISSUE TITLE
Replace ffmpeg and sox dependencies by using pydub

### ISSUE THREAD

**Issue by oadams** [oadams/persephone#23]

**Comment by oadams** [comment]
Pydub can deal with wav files in pure python. For coping with mp3's it needs ffmpeg to be installed. Not sure if this will cause a problem on windows.

Option 1) is to keep using ffmpeg as a dependency and expect windows users to use docker.
 Option 2) is to try and handle ffmpeg dependency being installed on windows. 
Option 3) is to require WAV files for persephone. Then the system can generalize across operating systems at the loss of functionality.

**Comment by alexis-michaud** [comment]
WAV files as default: yes, by all means! Only allowing WAV input would be a good way to clarify to users that their master files should never be in MP3 format.

In case you want a paragraph on this topic for the documentation, here is a note about why WAV is better.

> Phoneticians recommend using WAV-PCM (a noncompressed format) and _not_ MP3, which has lossy compression, i.e. irretrievable loss of information. MP3 is great to decrease file size for online distribution and the audio quality is OK for ordinary listening, but it is not recommended for hi-fi playback, phonetic analysis, or speech processing. To be more specific: MP3 is not that bad for extracting fundamental frequency (though it adds some indeterminacy: see Fuchs and Maxwell 2016), but not to be trusted for fine acoustic analysis and speech processing. (For details: van Son 2002). 

Refs:
Fuchs, Robert & Olga Maxwell. 2016. The effects of mp3 compression on acoustic measurements of fundamental frequency and pitch range. _Proceedings of Speech Prosody 2016_. 523–527.
van Son, Rob J.J.H. 2002. Can standard analysis tools be used on decompressed speech? _Proceedings of COCOSDA 2002: Workshop of the International Committee for the Coordination and Standardisation of Speech Databases and Assessment Techniques_.

At the Pangloss Collection & the Cocoon repository, curators are adamant (rightly in my view) abut only accepting WAV. MP3 is used among other options for download (for slow connections, download to smartphones...). It happened that depositors came with MP3 files and had lost the analog original; what Séverine did was convert their MP3 files to WAV. This is paradoxical, because it increases the file size without improving the quality (the information lost in the process of MP3 compression is irretrievably lost). The idea was to ensure consistency of the file format in the archive: if we accepted MP3 as the format for original files, a visitor might erroneously conclude that MP3 is fine as the format for the master file.

**Comment by oadams** [comment]
Okay, fantastic. Thanks for the comments. I've changed the README.md to only claim support of WAV files and will remove the ffmpeg dependency and use pydub instead.

**Comment by oadams** [comment]
So it looks like pydub can only change wav file sample rates / channels / frame widths via calls to ffmpeg. However:
- python_speech_features (where the wavs ultimately go) can cope with varying sample rates
- scipy.io.wavfile.read can read a few different types (8bit,16bit,32bit).

I'd need to do some testing to make sure wav normalization works consistently and results in the same speech features, but it could be worth it to ditch the ffmpeg dependency.

**Comment by oadams** [comment]
It doesn't look like this is going to be feasible any time soon. Some reasons off the top of my head:
- scipy.io.wavfile.read doesn't support 24bit WAVs. They need to be supported.
- Enforcing WAVs as input may be good most of the time, but sometimes users will not have WAVs. This may be for fairly reasons, such as an ELAN file using an MP4 media resource (so I actually need this functionality for my own experiments right now). Other times it may be bad practice on the part of the user: they happened to archive their data as an MP3. The thing is, persephone can't encourage best practice in this case since the collection of audio has already happened.

**Comment by solaris573** [comment]
@oadams Sorry for necroing an old, closed issue. I was searching around for a replacement for pydub (memory usage is high for my use case) when I came across this issue.

pydub also uses ffmpeg as you noted, and instead of bundling a 50mb EXE with my releases I decided to use the `imageio` library.

```
import imageio
imageio.plugins.ffmpeg.download()
```

It will download ffmpeg and put it in an accessible place if it's not found on the system, or it will do nothing if it detects ffmpeg is already installed somewhere accessible. I wrote my program using Ubuntu and test with Windows, and it works well in both cases. It's independent of pydub so it could be a potential solution for automatically downloading and installing ffmpeg for Windows users if you don't mind adding another dependency to your project.

I can't say I'm too familiar with your project so forgive me if this isn't helpful for your use case, but I figured I'd leave a comment since I was solving a similar issue just the other day.

**Comment by shuttle1987** [comment]
@solaris573 thanks for the suggestion, I'll look into it when I get some time.

**Comment by oadams** [comment]
@solaris573 Hi Solaris. Thanks for bringing this up, don't apologize for the necroing :grinning: This sounds like a solid way to sidestep the above issues. I've made a new issue (#139). Cheers!

**Comment by oadams** [comment]
Cheers!
