### ISSUE TITLE
Remove nltk_contrib dependency

### ISSUE THREAD

**Issue by shuttle1987** [oadams/persephone#32]
Currently we use nltk_contrib for use with TextGrids
```
from nltk_contrib.textgrid import TextGrid
```
Unfortunately nltk_contrib is not on PyPi and this makes installation a bit annoying. It appears that we already depend on https://pypi.python.org/pypi/pympi-ling/ which supports TextGrid. I propose using this library if it is easier to install.

**Comment by shuttle1987** [comment]
If you need a TextGrid that has the iter protocol let me know, we can patch that other library or perhaps PR to that library.

**Comment by oadams** [comment]
So I actually tried using pympi.Praat.TextGrid to read the TextGrid files that get used in datasets/butcher.py some time ago and it wouldn't load them. I can't recall the exact issue but patching the library does seem a way to go. I'm actually going to remove the datasets/butcher.py for now since it's (a) no longer functional due to non-backwards compatible changes and (b) it's not an open corpus so other people can't use it and thus it doesn't really belong in the repository.

Removing datasets/butcher.py technically satisfies this issue, but perhaps not closing this is a good idea since it's fairly important to get support for Praat. Basically after ELAN (almost done now) and Praat (#30 ) we're good.
