### ISSUE TITLE
Decide whether to do relative imports versus from persephone.blah import *

### ISSUE THREAD

**Issue by oadams** [oadams/persephone#58]
What approach do good project use?

**Comment by shuttle1987** [comment]
Once upon a time relative imports were broken somewhat so the suggestion was always to do explicit imports. Now there's a bit more choice since implicit relative imports are not a problem anymore, see: https://mail.python.org/pipermail/python-dev/2010-October/104476.html

Given you are installing the package with setuptools you can use absolute imports everywhere and everything will work because the package name will be on the path. Explicit relative imports (the only type of relative import supported by python3) will also work.

**Comment by oadams** [comment]
Ok, cool. Let's stick with relative if it's fine.
