### ISSUE TITLE
Potentially remove support for Python 3.5

### ISSUE THREAD

**Issue by oadams** [oadams/persephone#95]
I removed support for 3.4 some days ago now. I'm considering the more radical idea of removing support for 3.5 too and looking towards the future.

Pros:
- PEP 498 formatted string literals are delightful.
- typing.NamedTuples can be described with an elegant syntax:
```
class Thing(NamedTuple):
     some_attribute: str
     another_attribute: int
```
This actually is useful for documentation with sphinx because typed NamedTuples with the old syntax aren't supported very well: typing information is not automatically included, unlike as is the case for functions when the sphinx_autodoc_typehints extension is used.
- os.PathLike interface could help with changing string paths to pathlib.Paths I guess, though ideally I'd just do a complete swap anyway in which case it doesn't make a difference.
- There should be no issues deploying 3.6 in Docker, which is how most non-technical users are using the tool right now. Later when pyinstaller is used, the problem will also be avoided. For technical users, it's not hard to install python3.6.

Cons:
- There's no critical reason to drop support. None of the reasons above are that killer.
- Installing Python 3.6 even for a techincal user (suppose they're on Ubuntu 16.04) could be just enough friction not to install.

**Comment by shuttle1987** [comment]
As far as I know Debian 8 only supports python 3.4 and Debian 9 supports 3.5. This means you would force users to install something that's not in the official repos in order to get this library working. That could be a substantial barrier to entry as PyInstaller doesn't do cross-compilation (see https://pyinstaller.readthedocs.io/en/stable/operating-mode.html) and you'd end up running into this problem again. I've had a few attempts at setting up a cross compilation tool chain but it is a substantial pain to do (my most recent work in progress is here: https://github.com/shuttle1987/conditional_python_compilation)

Now I think both other issues can be worked around with Python 3.5.
- fstrings https://github.com/asottile/future-fstrings very brilliant backport of f-strings to earlier python versions
- namedtuples  there's a number of ways of getting around this. There's always the class + __slots__ approach. Among others

**Comment by oadams** [comment]
Thanks for the thoughts! It all makes a lot of sense. Yeah, let's keep 3.5 around. I've added future-fstrings to setup.py. 3.4 was dropped because of typing stuff the code uses now that was added in 3.5.
